// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9c_Sn_URFcWyfmZd2HCGDrN6aB6hCmc',
    appId: '1:665185086396:web:5998924a188a73b83dd9b9',
    messagingSenderId: '665185086396',
    projectId: 'honomara-ranking',
    authDomain: 'honomara-ranking.firebaseapp.com',
    storageBucket: 'honomara-ranking.appspot.com',
    measurementId: 'G-ZWE81QZLXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmldTElnwavF63IhPSYoI3peyz0ptwlQU',
    appId: '1:665185086396:android:8d53fc5f73bb9b0b3dd9b9',
    messagingSenderId: '665185086396',
    projectId: 'honomara-ranking',
    storageBucket: 'honomara-ranking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8mtXBk43ubEXvYE_szhT0zqV_AKSC08',
    appId: '1:665185086396:ios:acd2c28fbd7724bb3dd9b9',
    messagingSenderId: '665185086396',
    projectId: 'honomara-ranking',
    storageBucket: 'honomara-ranking.appspot.com',
    iosBundleId: 'com.example.honomara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8mtXBk43ubEXvYE_szhT0zqV_AKSC08',
    appId: '1:665185086396:ios:acd2c28fbd7724bb3dd9b9',
    messagingSenderId: '665185086396',
    projectId: 'honomara-ranking',
    storageBucket: 'honomara-ranking.appspot.com',
    iosBundleId: 'com.example.honomara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv9c_Sn_URFcWyfmZd2HCGDrN6aB6hCmc',
    appId: '1:665185086396:web:4e3de74783b938023dd9b9',
    messagingSenderId: '665185086396',
    projectId: 'honomara-ranking',
    authDomain: 'honomara-ranking.firebaseapp.com',
    storageBucket: 'honomara-ranking.appspot.com',
    measurementId: 'G-REKDV6HM3X',
  );
}
